# Generated by Django 5.1.5 on 2025-03-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_productgenric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgenric',
            name='product',
        ),
        migrations.AddField(
            model_name='productgenric',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
